#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H
//确定使用哪些外设驱动

//#define RTE_DEVICE_STARTUP_STM32F4xx    /* Device Startup for STM32F4 */
//以下外设所有f4板子通用
//#define RTE_DEVICE_STDPERIPH_ADC
//#define RTE_DEVICE_STDPERIPH_CRC
//#define RTE_DEVICE_STDPERIPH_DBGMCU
//#define RTE_DEVICE_STDPERIPH_DMA
//#define RTE_DEVICE_STDPERIPH_EXTI
//#define RTE_DEVICE_STDPERIPH_FLASH
#define RTE_DEVICE_STDPERIPH_GPIO
#define RTE_DEVICE_STDPERIPH_I2C
//#define RTE_DEVICE_STDPERIPH_IWDG
//#define RTE_DEVICE_STDPERIPH_PWR
#define RTE_DEVICE_STDPERIPH_RCC
//#define RTE_DEVICE_STDPERIPH_RTC
//#define RTE_DEVICE_STDPERIPH_SDIO
//#define RTE_DEVICE_STDPERIPH_SPI
//#define RTE_DEVICE_STDPERIPH_SYSCFG
#define RTE_DEVICE_STDPERIPH_TIM
#define RTE_DEVICE_STDPERIPH_USART
//#define RTE_DEVICE_STDPERIPH_WWDG

//以下外设各板子间有别
//#define RTE_DEVICE_STDPERIPH_CRYP
//#define RTE_DEVICE_STDPERIPH_HASH
//#define RTE_DEVICE_STDPERIPH_RNG
//#define RTE_DEVICE_STDPERIPH_CAN
//#define RTE_DEVICE_STDPERIPH_DAC
//#define RTE_DEVICE_STDPERIPH_DCMI
//#define RTE_DEVICE_STDPERIPH_DMA2D
//#define RTE_DEVICE_STDPERIPH_LTDC //STM32F429_439xx
//#define RTE_DEVICE_STDPERIPH_SAI

//有些问题
//#define RTE_DEVICE_STDPERIPH_FMC
//#define RTE_DEVICE_STDPERIPH_FSMC //STM32F40_41xxx

#endif /* RTE_COMPONENTS_H */
